### ISSUE TITLE
macro code is getting corrupted everytime i try to save it

### ISSUE THREAD

**Issue by Mr-P-D** [JohnWoodman/VBA-Macro-Reverse-Shell#1]
i am not able to execute the vba to get the shell

**Comment by JohnWoodman** [comment]
I'm going to need a little more explanation if you need help getting it to work.

**Comment by Mr-P-D** [comment]
when i am using the cam code mentioned in this repo and try to save file, i am seeing the error msg that corrupt code, i will get you some screenshots today

**
![image](https://user-images.githubusercontent.com/14123680/133265602-cc8c1deb-d8da-419a-a988-816a055b8624.png)
**

**Comment by JohnWoodman** [comment]
You can try deleting the comments in the code. I've never ran into this issue, so I'm not entirely sure.
